"""Live and paper execution contracts, routing, adapters, and reconciliation."""

from fxbot.execution.adapters import MT5BrokerAdapter, MT5ExecutionConfig
from fxbot.execution.broker import (
    BrokerAdapter,
    ExecutionError,
    FillSink,
    OrderNotFoundError,
    OrderSink,
    PermanentBrokerError,
    RiskAuthorizer,
    TransientBrokerError,
    UnknownSubmissionError,
    ensure_unique_fills,
)
from fxbot.execution.connection import (
    MT5ConnectionManager,
    MT5ConnectionSnapshot,
    MT5ExecutionClient,
    MT5ExecutionConnectionConfig,
    ReconnectPolicy,
)
from fxbot.execution.idempotency import (
    IdempotencyConflictError,
    IdempotencyRecord,
    InMemoryIdempotencyStore,
)
from fxbot.execution.lifecycle import (
    InvalidOrderTransitionError,
    transition_allowed,
    validate_transition,
    with_status,
)
from fxbot.execution.models import (
    BrokerOrder,
    ExecutionEvent,
    ExecutionEventKind,
    ExecutionFill,
    ExecutionMode,
    Metadata,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    Quote,
    RiskDecision,
    TimeInForce,
)
from fxbot.execution.mt5_mapping import (
    MT5SymbolSpec,
    build_mt5_request,
    client_order_comment,
    normalize_price,
    normalize_volume,
    validate_entry_prices,
    validate_freeze_distance,
)
from fxbot.execution.mt5_recovery import (
    MT5RetcodeCategory,
    MT5RetcodeClassification,
    classification_from_result,
    classify_mt5_retcode,
    raise_for_mt5_result,
)
from fxbot.execution.paper import PaperBroker, PaperBrokerConfig
from fxbot.execution.reconciliation import (
    LiveMT5Reconciler,
    MT5PositionSnapshot,
    MT5ReconciliationReport,
    ReconciliationIssue,
    ReconciliationIssueKind,
)
from fxbot.execution.router import AllowAllRiskAuthorizer, ExecutionRouter, RetryPolicy
from fxbot.execution.runtime import ExecutionRuntime, SyncResult
from fxbot.execution.safety import ExecutionControl, ExecutionControlState

__all__ = [
    "AllowAllRiskAuthorizer",
    "BrokerAdapter",
    "BrokerOrder",
    "ExecutionControl",
    "ExecutionControlState",
    "ExecutionError",
    "ExecutionEvent",
    "ExecutionEventKind",
    "ExecutionFill",
    "ExecutionMode",
    "ExecutionRouter",
    "ExecutionRuntime",
    "FillSink",
    "IdempotencyConflictError",
    "IdempotencyRecord",
    "InMemoryIdempotencyStore",
    "InvalidOrderTransitionError",
    "LiveMT5Reconciler",
    "MT5BrokerAdapter",
    "MT5ConnectionManager",
    "MT5ConnectionSnapshot",
    "MT5ExecutionClient",
    "MT5ExecutionConfig",
    "MT5ExecutionConnectionConfig",
    "MT5PositionSnapshot",
    "MT5ReconciliationReport",
    "MT5RetcodeCategory",
    "MT5RetcodeClassification",
    "MT5SymbolSpec",
    "Metadata",
    "OrderIntent",
    "OrderNotFoundError",
    "OrderSide",
    "OrderSink",
    "OrderStatus",
    "OrderType",
    "PaperBroker",
    "PaperBrokerConfig",
    "PermanentBrokerError",
    "Quote",
    "ReconciliationIssue",
    "ReconciliationIssueKind",
    "ReconnectPolicy",
    "RetryPolicy",
    "RiskAuthorizer",
    "RiskDecision",
    "SyncResult",
    "TimeInForce",
    "TransientBrokerError",
    "UnknownSubmissionError",
    "build_mt5_request",
    "classification_from_result",
    "classify_mt5_retcode",
    "client_order_comment",
    "ensure_unique_fills",
    "normalize_price",
    "normalize_volume",
    "raise_for_mt5_result",
    "transition_allowed",
    "validate_entry_prices",
    "validate_freeze_distance",
    "validate_transition",
    "with_status",
]
