"""Immutable contracts for live and paper execution workflows."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from hashlib import sha256
from math import isfinite
from typing import TypeAlias

Metadata: TypeAlias = tuple[tuple[str, str], ...]


def _utc(value: datetime, field_name: str) -> datetime:
    if value.tzinfo is None or value.utcoffset() is None:
        raise ValueError(f"{field_name} must be timezone-aware")
    return value.astimezone(UTC)


def _identifier(value: str, field_name: str) -> str:
    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field_name} cannot be empty")
    return normalized


def _symbol(value: str) -> str:
    normalized = value.strip().upper()
    if not normalized:
        raise ValueError("symbol cannot be empty")
    return normalized


def _positive(value: float, field_name: str) -> float:
    number = float(value)
    if not isfinite(number) or number <= 0.0:
        raise ValueError(f"{field_name} must be a positive finite number")
    return number


def _non_negative(value: float, field_name: str) -> float:
    number = float(value)
    if not isfinite(number) or number < 0.0:
        raise ValueError(f"{field_name} must be finite and non-negative")
    return number


def _metadata(value: Metadata) -> Metadata:
    normalized: list[tuple[str, str]] = []
    seen: set[str] = set()
    for raw_key, raw_value in value:
        key = _identifier(raw_key, "metadata key")
        if key in seen:
            raise ValueError(f"Duplicate metadata key: {key}")
        seen.add(key)
        normalized.append((key, str(raw_value)))
    return tuple(sorted(normalized))


class ExecutionMode(StrEnum):
    """Where an order is routed."""

    PAPER = "paper"
    LIVE = "live"


class OrderSide(StrEnum):
    """Executable order direction."""

    BUY = "buy"
    SELL = "sell"

    @property
    def sign(self) -> float:
        return 1.0 if self is OrderSide.BUY else -1.0

    @property
    def opposite(self) -> OrderSide:
        return OrderSide.SELL if self is OrderSide.BUY else OrderSide.BUY


class OrderType(StrEnum):
    """Supported broker order instructions."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class TimeInForce(StrEnum):
    """Supported order lifetimes."""

    GTC = "gtc"
    IOC = "ioc"
    FOK = "fok"
    DAY = "day"


class OrderStatus(StrEnum):
    """Durable order lifecycle states."""

    CREATED = "created"
    VALIDATED = "validated"
    SUBMITTED = "submitted"
    ACKNOWLEDGED = "acknowledged"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCEL_PENDING = "cancel_pending"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"
    UNKNOWN = "unknown"

    @property
    def terminal(self) -> bool:
        return self in {
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        }

    @property
    def active(self) -> bool:
        return self in {
            OrderStatus.SUBMITTED,
            OrderStatus.ACKNOWLEDGED,
            OrderStatus.PARTIALLY_FILLED,
            OrderStatus.CANCEL_PENDING,
        }


class ExecutionEventKind(StrEnum):
    """Audit event categories generated by the execution layer."""

    SAFETY_BLOCKED = "safety_blocked"
    RISK_APPROVED = "risk_approved"
    RISK_REJECTED = "risk_rejected"
    ORDER_SUBMITTED = "order_submitted"
    ORDER_ACKNOWLEDGED = "order_acknowledged"
    ORDER_REJECTED = "order_rejected"
    ORDER_CANCEL_REQUESTED = "order_cancel_requested"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_EXPIRED = "order_expired"
    FILL = "fill"
    RETRY = "retry"
    DUPLICATE_SUPPRESSED = "duplicate_suppressed"
    RECONCILIATION_WARNING = "reconciliation_warning"


@dataclass(frozen=True, slots=True)
class OrderIntent:
    """Strategy-originated instruction before broker submission."""

    client_order_id: str
    idempotency_key: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    created_at: datetime
    time_in_force: TimeInForce = TimeInForce.GTC
    limit_price: float | None = None
    stop_price: float | None = None
    reduce_only: bool = False
    strategy_id: str = "strategy"
    metadata: Metadata = ()

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "client_order_id",
            _identifier(self.client_order_id, "client_order_id"),
        )
        object.__setattr__(
            self,
            "idempotency_key",
            _identifier(self.idempotency_key, "idempotency_key"),
        )
        object.__setattr__(self, "symbol", _symbol(self.symbol))
        object.__setattr__(self, "side", OrderSide(self.side))
        object.__setattr__(self, "order_type", OrderType(self.order_type))
        object.__setattr__(self, "quantity", _positive(self.quantity, "quantity"))
        object.__setattr__(self, "created_at", _utc(self.created_at, "created_at"))
        object.__setattr__(self, "time_in_force", TimeInForce(self.time_in_force))
        object.__setattr__(self, "strategy_id", self.strategy_id.strip() or "strategy")
        object.__setattr__(self, "metadata", _metadata(self.metadata))

        if self.limit_price is not None:
            object.__setattr__(self, "limit_price", _positive(self.limit_price, "limit_price"))
        if self.stop_price is not None:
            object.__setattr__(self, "stop_price", _positive(self.stop_price, "stop_price"))

        if self.order_type is OrderType.MARKET:
            if self.limit_price is not None or self.stop_price is not None:
                raise ValueError("MARKET orders cannot define limit_price or stop_price")
        elif self.order_type is OrderType.LIMIT:
            if self.limit_price is None or self.stop_price is not None:
                raise ValueError("LIMIT orders require only limit_price")
        elif self.order_type is OrderType.STOP:
            if self.stop_price is None or self.limit_price is not None:
                raise ValueError("STOP orders require only stop_price")
        elif self.limit_price is None or self.stop_price is None:
            raise ValueError("STOP_LIMIT orders require stop_price and limit_price")

    @property
    def semantic_fingerprint(self) -> str:
        payload = (
            self.client_order_id,
            self.symbol,
            self.side.value,
            self.order_type.value,
            self.quantity,
            self.time_in_force.value,
            self.limit_price,
            self.stop_price,
            self.reduce_only,
            self.strategy_id,
            self.metadata,
        )
        return sha256(repr(payload).encode()).hexdigest()


@dataclass(frozen=True, slots=True)
class BrokerOrder:
    """Broker-side state for an acknowledged or terminal order."""

    broker_order_id: str
    client_order_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    status: OrderStatus
    requested_quantity: float
    filled_quantity: float
    average_fill_price: float | None
    submitted_at: datetime
    updated_at: datetime
    rejection_reason: str | None = None
    metadata: Metadata = ()

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "broker_order_id",
            _identifier(self.broker_order_id, "broker_order_id"),
        )
        object.__setattr__(
            self,
            "client_order_id",
            _identifier(self.client_order_id, "client_order_id"),
        )
        object.__setattr__(self, "symbol", _symbol(self.symbol))
        object.__setattr__(self, "side", OrderSide(self.side))
        object.__setattr__(self, "order_type", OrderType(self.order_type))
        object.__setattr__(self, "status", OrderStatus(self.status))
        object.__setattr__(
            self,
            "requested_quantity",
            _positive(self.requested_quantity, "requested_quantity"),
        )
        object.__setattr__(
            self,
            "filled_quantity",
            _non_negative(self.filled_quantity, "filled_quantity"),
        )
        object.__setattr__(self, "submitted_at", _utc(self.submitted_at, "submitted_at"))
        object.__setattr__(self, "updated_at", _utc(self.updated_at, "updated_at"))
        object.__setattr__(self, "metadata", _metadata(self.metadata))

        if self.updated_at < self.submitted_at:
            raise ValueError("updated_at cannot predate submitted_at")
        if self.filled_quantity > self.requested_quantity + 1e-12:
            raise ValueError("filled_quantity cannot exceed requested_quantity")
        if self.average_fill_price is not None:
            object.__setattr__(
                self,
                "average_fill_price",
                _positive(self.average_fill_price, "average_fill_price"),
            )
        if self.filled_quantity > 0.0 and self.average_fill_price is None:
            raise ValueError("Filled orders require average_fill_price")
        if self.status is OrderStatus.FILLED and (
            abs(self.filled_quantity - self.requested_quantity) > 1e-12
        ):
            raise ValueError("FILLED orders require full requested quantity")
        if self.status is OrderStatus.PARTIALLY_FILLED and not (
            0.0 < self.filled_quantity < self.requested_quantity
        ):
            raise ValueError("PARTIALLY_FILLED requires partial quantity")
        if self.status is OrderStatus.REJECTED and not self.rejection_reason:
            raise ValueError("REJECTED orders require rejection_reason")

    @property
    def remaining_quantity(self) -> float:
        return max(self.requested_quantity - self.filled_quantity, 0.0)


@dataclass(frozen=True, slots=True)
class ExecutionFill:
    """One broker execution report."""

    execution_id: str
    broker_order_id: str
    client_order_id: str
    symbol: str
    side: OrderSide
    quantity: float
    price: float
    executed_at: datetime
    commission: float = 0.0
    liquidity: str = "unknown"
    metadata: Metadata = ()

    def __post_init__(self) -> None:
        object.__setattr__(self, "execution_id", _identifier(self.execution_id, "execution_id"))
        object.__setattr__(
            self,
            "broker_order_id",
            _identifier(self.broker_order_id, "broker_order_id"),
        )
        object.__setattr__(
            self,
            "client_order_id",
            _identifier(self.client_order_id, "client_order_id"),
        )
        object.__setattr__(self, "symbol", _symbol(self.symbol))
        object.__setattr__(self, "side", OrderSide(self.side))
        object.__setattr__(self, "quantity", _positive(self.quantity, "quantity"))
        object.__setattr__(self, "price", _positive(self.price, "price"))
        object.__setattr__(self, "executed_at", _utc(self.executed_at, "executed_at"))
        object.__setattr__(self, "commission", _non_negative(self.commission, "commission"))
        object.__setattr__(self, "liquidity", self.liquidity.strip() or "unknown")
        object.__setattr__(self, "metadata", _metadata(self.metadata))


@dataclass(frozen=True, slots=True)
class Quote:
    """Current executable bid/ask quote."""

    symbol: str
    bid: float
    ask: float
    timestamp: datetime

    def __post_init__(self) -> None:
        object.__setattr__(self, "symbol", _symbol(self.symbol))
        object.__setattr__(self, "bid", _positive(self.bid, "bid"))
        object.__setattr__(self, "ask", _positive(self.ask, "ask"))
        object.__setattr__(self, "timestamp", _utc(self.timestamp, "timestamp"))
        if self.ask < self.bid:
            raise ValueError("ask cannot be below bid")

    @property
    def spread(self) -> float:
        return self.ask - self.bid

    @property
    def mid(self) -> float:
        return (self.bid + self.ask) / 2.0


@dataclass(frozen=True, slots=True)
class RiskDecision:
    """Pre-trade authorization result."""

    approved: bool
    reason: str
    approved_quantity: float | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "reason", self.reason.strip() or "unspecified")
        if self.approved_quantity is not None:
            object.__setattr__(
                self,
                "approved_quantity",
                _positive(self.approved_quantity, "approved_quantity"),
            )
        if not self.approved and self.approved_quantity is not None:
            raise ValueError("Rejected decisions cannot approve quantity")


@dataclass(frozen=True, slots=True)
class ExecutionEvent:
    """Append-only execution audit record."""

    sequence: int
    timestamp: datetime
    kind: ExecutionEventKind
    message: str
    client_order_id: str | None = None
    broker_order_id: str | None = None
    execution_id: str | None = None
    metadata: Metadata = ()

    def __post_init__(self) -> None:
        if self.sequence < 0:
            raise ValueError("sequence must be non-negative")
        object.__setattr__(self, "timestamp", _utc(self.timestamp, "timestamp"))
        object.__setattr__(self, "kind", ExecutionEventKind(self.kind))
        object.__setattr__(self, "message", self.message.strip() or self.kind.value)
        if self.client_order_id is not None:
            object.__setattr__(
                self,
                "client_order_id",
                _identifier(self.client_order_id, "client_order_id"),
            )
        if self.broker_order_id is not None:
            object.__setattr__(
                self,
                "broker_order_id",
                _identifier(self.broker_order_id, "broker_order_id"),
            )
        if self.execution_id is not None:
            object.__setattr__(
                self,
                "execution_id",
                _identifier(self.execution_id, "execution_id"),
            )
        object.__setattr__(self, "metadata", _metadata(self.metadata))
