"""Deterministic event-driven historical simulation."""

from fxbot.backtest.broker import (
    BrokerSnapshot,
    ClosedTrade,
    NetPosition,
    SimulatedBroker,
)
from fxbot.backtest.clock import HistoricalClock, HistoricalClockError
from fxbot.backtest.config import (
    BacktestConfig,
    CommissionConfig,
    ExecutionConfig,
    InstrumentConfig,
    SlippageConfig,
    SwapConfig,
)
from fxbot.backtest.drawdown import (
    DrawdownAnalysis,
    DrawdownPeriod,
    analyze_drawdowns,
)
from fxbot.backtest.engine import (
    AllowAllRiskGate,
    BacktestEngine,
    BacktestStrategy,
    FillObserver,
    RiskGate,
    RiskGateResult,
    StrategyDecisionAdapter,
)
from fxbot.backtest.events import (
    AuditEvent,
    BacktestEvent,
    EventKind,
    MarketEvent,
    OrderRequest,
    OrderSide,
    OrderState,
    OrderStatus,
    OrderType,
    SimulatedFill,
    TimeInForce,
    market_record_time,
)
from fxbot.backtest.metrics import (
    BenchmarkComparison,
    PerformanceMetrics,
    PeriodReturn,
    calculate_performance,
    calendar_returns,
    compare_benchmark,
    drawdown_metrics,
    equity_returns,
)
from fxbot.backtest.monte_carlo import (
    MonteCarloConfig,
    MonteCarloMethod,
    MonteCarloPath,
    MonteCarloQuantile,
    MonteCarloResult,
    simulate_monte_carlo,
)
from fxbot.backtest.reporting import (
    PerformanceBreakdown,
    PerformanceReport,
    build_performance_report,
)
from fxbot.backtest.results import BacktestResult, EquityPoint, equity_point
from fxbot.backtest.trades import TradeExcursion, TradeStatistics, analyze_trades

__all__ = [
    "AllowAllRiskGate",
    "AuditEvent",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestEvent",
    "BacktestResult",
    "BacktestStrategy",
    "BenchmarkComparison",
    "BrokerSnapshot",
    "ClosedTrade",
    "CommissionConfig",
    "DrawdownAnalysis",
    "DrawdownPeriod",
    "EquityPoint",
    "EventKind",
    "ExecutionConfig",
    "FillObserver",
    "HistoricalClock",
    "HistoricalClockError",
    "InstrumentConfig",
    "MarketEvent",
    "MonteCarloConfig",
    "MonteCarloMethod",
    "MonteCarloPath",
    "MonteCarloQuantile",
    "MonteCarloResult",
    "NetPosition",
    "OrderRequest",
    "OrderSide",
    "OrderState",
    "OrderStatus",
    "OrderType",
    "PerformanceBreakdown",
    "PerformanceMetrics",
    "PerformanceReport",
    "PeriodReturn",
    "RiskGate",
    "RiskGateResult",
    "SimulatedBroker",
    "SimulatedFill",
    "SlippageConfig",
    "StrategyDecisionAdapter",
    "SwapConfig",
    "TimeInForce",
    "TradeExcursion",
    "TradeStatistics",
    "analyze_drawdowns",
    "analyze_trades",
    "build_performance_report",
    "calculate_performance",
    "calendar_returns",
    "compare_benchmark",
    "drawdown_metrics",
    "equity_point",
    "equity_returns",
    "market_record_time",
    "simulate_monte_carlo",
]
